apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot
spec:
  ingressClassName: kong
  rules:
  - host: 'example.com'
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: springboot-kong
            port:
              number: 8080